FIRE_DMG = 5
FIRE_BUILDUP_LIMIT = 4
UPWARD_PRESSURE_THRESHOLD = 3.0
FALL_DMG_MULT = 5
CAVEIN_DMG_MULT = 10
SWIMMABLE_THRESHOLD = 1.0
DROWNING_LEVEL_THRESHOLD = 3.5
BREATH_LOSS = 8
DRYING_THRESHOLD = 0.5
DRYING_AMT = 0.01
WATER_HORIZONTAL_THRESHOLD = 0.2 # 0 for nl < level_z
CRITTER_HIDE_THRESHOLD = 10
PREDATOR_FOV_RADIUS = 6

EDGE_MAP = [
    [1, 1, 1],
    [1, 0, 1],
    [1, 1, 1],
]
